### error

```go
err = errors.New("message")
```

### panic

panic会让程序崩溃，中断运行

```go
panic("message")
```

### recover

recover让程序在出现异常时可以继续运行

```go
defer func(){
    recover()
}()

//或者打印异常信息
defer func(){
    if err := recover();err != nil{
        fmt.Println(err)
        //注意参数不能写成recover(),因为没有打印异常
    }
}()
```

